### ISSUE TITLE
Randomize initial data display order

### ISSUE THREAD

**Issue by Aramai** [olestourko/open-tech-pay#3]
I would suggest randomizing the initial display of data on the page given the current small result set. Displaying in submission order makes it easy for co-workers / friends entering data close together to fairly easily pick out what data belongs to whom.

**Comment by olestourko** [comment]
Good point; added an option to toggle market data randomisation with c9d7c86bd294fb96e74091eb573cfa76d703cc7e and 1dfaebc4a52789d7adacaedfb28c2468c5448fb5.


People can still piece together the order of submissions if they really want to by looking at the submission dates or changing the browser JS, but this should be good enough.
